### ISSUE TITLE
piss system

### ISSUE THREAD

**Issue by jordancambridge** [christianbookout/rome-plugin#7]
guys, we need to have a working piss system for my immersion (need to pee)

ijf not i dont think the server will take off, here is a diagram;:

![image](https://user-images.githubusercontent.com/95837825/145744555-27774dc3-e8e7-49f9-9819-9d8d43d58b8c.png)

peeing in thew toilet for examaple

please add or else i will copyright strike and cease and desist you on behalf of the roman empire thanks

**Comment by christianbookout** [comment]
maybe
